import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const pages = await (await fetch('http://127.0.0.1:9222/json/list')).json();
const page = pages.find(p => p.type === 'page' && p.url.includes('4173'));
assert.ok(page, 'Local game tab exists');
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
let id = 0; const pending = new Map(), errors = [];
ws.onmessage = e => { const data = JSON.parse(e.data); if (data.id) { const p = pending.get(data.id); pending.delete(data.id); if (data.error) p.reject(data.error); else p.resolve(data.result); } else if (data.method === 'Runtime.exceptionThrown') errors.push(data.params.exceptionDetails.text + ': ' + data.params.exceptionDetails.exception?.description); };
const send = (method, params = {}) => new Promise((resolve, reject) => { const n = ++id; pending.set(n, { resolve, reject }); ws.send(JSON.stringify({ id: n, method, params })); });
const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text); return r.result.value; };
await send('Runtime.enable'); await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
await send('Page.reload', { ignoreCache: true });
for (let i = 0; i < 100; i++) { try { if (await evaluate('!!window.ironTide')) break; } catch {} await new Promise(r => setTimeout(r, 50)); }
await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
await writeFile('/tmp/iron-tide-briefing.png', Buffer.from((await send('Page.captureScreenshot', { format: 'png' })).data, 'base64'));
assert.equal(await evaluate('!!window.ironTide'), true);
await evaluate('document.getElementById("start").click()');
assert.equal(await evaluate('ironTide.started'), true);
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'd', code: 'KeyD' });
await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'd', code: 'KeyD' });
assert.equal(await evaluate('ironTide.game.owned(0,"yard").length'), 1, 'D deploys MCV');
await evaluate('document.getElementById("pause").click()');
assert.equal(await evaluate('ironTide.paused'), true);
await evaluate('document.querySelector("[data-type=power]").click()');
assert.equal(await evaluate('ironTide.game.players[0].queues.structures[0].type'), 'power');
await evaluate('for(let i=0;i<210;i++)ironTide.game.step(.1);ironTide.processEvents();ironTide.updateUI(true)');
await evaluate('document.querySelector("[data-type=power]").click()');
assert.equal(await evaluate('ironTide.renderer.placement'), 'power');
const pos = await evaluate('(()=>{const p=ironTide.renderer.toScreen(28,54),r=document.getElementById("battle").getBoundingClientRect();return{x:p.x+r.left,y:p.y+r.top}})()');
await send('Input.dispatchMouseEvent', { type: 'mouseMoved', ...pos });
await send('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...pos });
await send('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, ...pos });
assert.equal(await evaluate('ironTide.game.owned(0,"power").length'), 1, 'Structure placed with real mouse input');
await evaluate('document.getElementById("help").click()'); assert.equal(await evaluate('document.getElementById("manual").hidden'), false);
await evaluate('document.getElementById("close-help").click()'); assert.equal(await evaluate('ironTide.paused'), true, 'Closing manual preserves paused state');
await evaluate('document.getElementById("speed").click()'); assert.equal(await evaluate('ironTide.speed'), 2);
await evaluate('document.getElementById("pause").click()'); assert.equal(await evaluate('ironTide.paused'), false);
await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
await writeFile('/tmp/iron-tide-gameplay.png', Buffer.from((await send('Page.captureScreenshot', { format: 'png' })).data, 'base64'));
const stats = await evaluate('({canvas:{w:document.getElementById("battle").width,h:document.getElementById("battle").height},time:ironTide.game.time,selected:[...ironTide.renderer.selected],buildCards:document.querySelectorAll(".build-card").length,bodyWidth:document.body.scrollWidth,windowWidth:innerWidth})');
assert.equal(stats.bodyWidth, stats.windowWidth, 'No horizontal page overflow at desktop size');
// A staged combat fixture exercises every sprite and the remaining real input paths.
await evaluate(`(()=>{
  document.getElementById('pause').click();
  const {game:g,renderer:r}=ironTide;g.ai.nextThink=Infinity;
  for(const [type,x,y]of[['refinery',20,51],['barracks',24,50],['factory',28,51],['shipyard',27,43],['gun',34,48]])g.spawn(type,0,x,y);
  for(const [type,x,y]of[['miner',18,54],['tank',29,48],['tank',30,49],['infantry',28,49],['infantry',29,50],['sub',23,41],['sub',26,40],['cruiser',23,44],['cruiser',27,42],['transport',31,45]])g.spawn(type,0,x,y);
  g.spawn('cruiser',1,23,34);g.spawn('destroyer',1,21,34);
  for(let i=0;i<45;i++)g.step(.1);
  r.center(27,47);r.camera.zoom=.9;
  ironTide.select([g.owned(0,'cruiser')[0].id]);
  document.querySelector('[data-tab=fleet]').click();
  ironTide.updateUI(true);ironTide.processEvents();
})()`);
assert.equal(await evaluate('document.querySelectorAll(".build-card").length'), 3, 'Soviet navy has cruiser, submarine, transport');
const transportPos = await evaluate('(()=>{const t=ironTide.game.owned(0,"transport")[0],p=ironTide.renderer.toScreen(t.x,t.y),r=document.getElementById("battle").getBoundingClientRect();return{x:p.x+r.left,y:p.y+r.top}})()');
await evaluate('ironTide.select([ironTide.game.owned(0,"tank")[0].id])');
await send('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'right', clickCount: 1, ...transportPos });
await send('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'right', clickCount: 1, ...transportPos });
assert.equal(await evaluate('ironTide.game.owned(0,"tank")[0].order.type'), 'board', 'Right-click a transport gives boarding order');
await evaluate('for(let i=0;i<180;i++)ironTide.game.step(.1);ironTide.updateUI(true)');
assert.ok(await evaluate('ironTide.game.owned(0,"transport")[0].cargo.length>0'), 'Tank physically boards transport');
await evaluate('ironTide.select([ironTide.game.owned(0,"transport")[0].id])');
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'u', code: 'KeyU' });
await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'u', code: 'KeyU' });
assert.equal(await evaluate('ironTide.game.owned(0,"transport")[0].cargo.length'), 0, 'U unloads transport through actual keyboard input');
await evaluate('ironTide.select(ironTide.game.owned(0,"cruiser").map(e=>e.id))');
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: '1', code: 'Digit1', modifiers: 2 });
await send('Input.dispatchKeyEvent', { type: 'keyUp', key: '1', code: 'Digit1' });
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' });
await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape' });
assert.equal(await evaluate('ironTide.renderer.selected.size'), 0);
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: '1', code: 'Digit1' });
await send('Input.dispatchKeyEvent', { type: 'keyUp', key: '1', code: 'Digit1' });
assert.equal(await evaluate('ironTide.renderer.selected.size'), 2, 'Control group restores both cruisers');
await evaluate('document.getElementById("pause").click(); document.getElementById("message-stack").replaceChildren()');
const timings = await evaluate('new Promise(resolve=>{const a=[];let last=performance.now();function f(t){a.push(t-last);last=t;if(a.length<90)requestAnimationFrame(f);else resolve(a.slice(3).sort((a,b)=>a-b))}requestAnimationFrame(f)})');
await writeFile('/tmp/iron-tide-battle.png', Buffer.from((await send('Page.captureScreenshot', { format: 'png' })).data, 'base64'));
await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 800, deviceScaleFactor: 1, mobile: false });
await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
assert.equal(await evaluate('document.body.scrollWidth===innerWidth'), true, 'No overflow at 1280px');
await writeFile('/tmp/iron-tide-1280.png', Buffer.from((await send('Page.captureScreenshot', { format: 'png' })).data, 'base64'));
// End-state overlay must be driven by the same all-buildings-and-MCV victory rule.
await evaluate('for(const e of ironTide.game.owned(1))if(e.type==="mcv"||["yard","power","refinery","barracks","factory","shipyard","gun"].includes(e.type))e.hp=0;ironTide.game.cleanup();ironTide.game.checkVictory();ironTide.processEvents()');
assert.equal(await evaluate('document.getElementById("result-title").textContent'), 'VICTORY');
assert.equal(await evaluate('document.getElementById("result").hidden'), false);
assert.equal(errors.length, 0, `No browser exceptions: ${errors.join('\n')}`);
console.log(JSON.stringify({ passed: true, stats, frameTimeMedian:timings[Math.floor(timings.length/2)], frameTimeP95:timings[Math.floor(timings.length*.95)], errors, screenshots: ['/tmp/iron-tide-briefing.png', '/tmp/iron-tide-gameplay.png', '/tmp/iron-tide-battle.png', '/tmp/iron-tide-1280.png'] }, null, 2));
ws.close();
