// Run with Playwright available (NODE_PATH is supported), using a disposable browser.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
const { chromium } = createRequire(import.meta.url)('playwright');
const server = spawn(process.execPath, ['server.mjs'], { env: { ...process.env, PORT: '4174' }, stdio: 'pipe' });
let browser;
try {
  await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => reject(new Error(`Server exited: ${code}`))); });
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1180, height: 820 }, hasTouch: true, isMobile: true });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4174');
  assert.equal(await page.evaluate(() => ironTide.renderer.terrain.ready), true, 'Photographic terrain atlas loads');
  await page.locator('#start').tap();
  await page.locator('#pause').tap();
  const snapshot = () => page.evaluate(() => ({ camera: { ...ironTide.renderer.camera }, selected: [...ironTide.renderer.selected], box: ironTide.renderer.selectionBox }));
  const client = await context.newCDPSession(page);
  const touch = async (type, points) => {
    await client.send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([x, y, id = 1]) => ({ x, y, id })) });
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  };
  const before = await snapshot();
  assert.equal(await page.locator('#battle').evaluate(el => getComputedStyle(el).touchAction), 'none');
  await touch('touchStart', [[450, 340]]);
  await touch('touchMove', [[520, 380]]);
  await touch('touchEnd', []);
  const after = await snapshot();
  assert.ok(after.camera.x < before.camera.x && after.camera.y < before.camera.y, 'Finger drag pans both axes');
  assert.deepEqual(after.selected, before.selected, 'Dragging preserves selection');
  assert.equal(after.box, null, 'Touch drag does not box-select');
  await page.locator('#battle').tap({ position: { x: 200, y: 200 } });
  assert.deepEqual((await snapshot()).camera, after.camera, 'A tap does not pan');
  await touch('touchStart', [[450, 340]]);
  await touch('touchCancel', []);
  await touch('touchStart', [[450, 340]]);
  await touch('touchMove', [[400, 340]]);
  await touch('touchEnd', []);
  assert.ok((await snapshot()).camera.x > after.camera.x, 'Drag works after cancellation');
  const mini = await page.locator('#minimap').boundingBox();
  const priorMini = (await snapshot()).camera;
  await touch('touchStart', [[mini.x + 30, mini.y + 30]]);
  await touch('touchMove', [[mini.x + 80, mini.y + 60]]);
  await touch('touchEnd', []);
  assert.notDeepEqual((await snapshot()).camera, priorMini, 'Minimap touch drag navigates');
  await page.mouse.move(400, 300);
  await page.mouse.down();
  await page.mouse.move(480, 350);
  assert.ok((await snapshot()).box, 'Mouse drag still box-selects');
  await page.mouse.up();
  for (const viewport of [{ width: 390, height: 844 }, { width: 375, height: 667 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(viewport);
    await page.reload();
    assert.equal(await page.evaluate(() => ironTide.renderer.terrain.ready), true, 'Terrain atlas loads on phone');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Phone layout fits viewport');
    await page.locator('#start').tap();
    await page.locator('#pause').tap();
    const original = await snapshot();
    const x = viewport.width / 2, y = viewport.height > 500 ? 300 : 170;
    await touch('touchStart', [[x - 30, y, 1], [x + 30, y, 2]]);
    await touch('touchMove', [[x - 65, y, 1], [x + 65, y, 2]]);
    const enlarged = await snapshot();
    assert.ok(enlarged.camera.zoom > original.camera.zoom, 'Pinch out zooms in');
    await touch('touchMove', [[x - 40, y, 1], [x + 40, y, 2]]);
    assert.ok((await snapshot()).camera.zoom < enlarged.camera.zoom, 'Pinch in zooms out');
    await touch('touchEnd', [[x - 40, y, 1]]);
    const oneFinger = await snapshot();
    await touch('touchMove', [[x + 60, y, 2]]);
    await touch('touchEnd', []);
    assert.ok((await snapshot()).camera.x < oneFinger.camera.x, 'Remaining finger pans without a jump');
    assert.deepEqual((await snapshot()).selected, original.selected, 'Pinch preserves selected unit');
    const zoom = (await snapshot()).camera.zoom;
    await page.locator('#zoom-out').tap();
    assert.ok((await snapshot()).camera.zoom < zoom, 'Zoom button works');
    await page.locator('#zoom-in').tap();
    await page.locator('#toggle-build').tap();
    assert.equal(await page.locator('#sidebar').isVisible(), true);
    await page.locator('#toggle-build').tap();
    assert.equal(await page.locator('#sidebar').isVisible(), false);
    await page.locator('#touch-order').tap();
    assert.match(await page.locator('#placement-hint').innerText(), /DESTINATION/);
    await page.locator('#touch-cancel').tap();
    assert.equal(await page.locator('#placement-hint').isVisible(), false);
    await page.screenshot({ path: `test-results/phone-${viewport.width}.png` });
  }
  assert.deepEqual(errors, []);
  console.log('Touch pan, tap, cancellation, minimap, and desktop selection passed.');
} finally {
  await browser?.close();
  server.kill();
}
